name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.3 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
      
    - name: Install Dependencies
      run: mix deps.get
      
    - name: Run Tests
      run: mix coveralls.github

  build:
    needs: test
    
    name: Build & Push

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: neptius/novy-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"

  deploy:
    needs: build

    name: Deploy

    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: novy-ressources
        dns-name-label: novy-api-dns
        image: neptius/novy-api:${{ github.sha }}
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}
        name: novy-api
        secure-environment-variables: DATABASE_URL=${{ secrets.DATABASE_URL }} SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
        location: 'westeurope'